### ISSUE TITLE
Cudagraph doesn't work anymore

### ISSUE THREAD

**Issue by FindHao** [pytorch-labs/tritonbench#110]
@xuzhao9 This PR https://github.com/pytorch-labs/tritonbench/pull/106 breaks the cudagraph execution of all ops in liger.

```
% git reset --hard 1fb46a37d012ed1a59709afd9735e0bed88e430c
HEAD is now at 1fb46a3 Enable cudagraph mode for kineto_trace (#106)
(ptd) testuser@server ➜ ~/ptd/tritonbench git:(main) ✗
% python run.py --op geglu --mode fwd  --precision fp32 --metrics latency,speedup,gpu_peak_mem,mem_footprint_compression_ratio --csv --cudagraph
  0%|                                                                                                                                                         | 0/4 [00:01<?, ?it/s]
Caught exception, terminating early with partial results
Traceback (most recent call last):
  File "/home/testuser/ptd/tritonbench/tritonbench/utils/triton_op.py", line 782, in run
    y_vals: Dict[str, BenchmarkOperatorMetrics] = functools.reduce(
                                                  ^^^^^^^^^^^^^^^^^
  File "/home/testuser/ptd/tritonbench/tritonbench/utils/triton_op.py", line 770, in _reduce_benchmarks
    acc[bm_name] = self._do_bench(
                   ^^^^^^^^^^^^^^^
  File "/home/testuser/ptd/tritonbench/tritonbench/utils/triton_op.py", line 1000, in _do_bench
    metrics.cpu_peak_mem, metrics.gpu_peak_mem = self.get_peak_mem(
                                                 ^^^^^^^^^^^^^^^^^^
  File "/home/testuser/ptd/tritonbench/tritonbench/utils/triton_op.py", line 1286, in get_peak_mem
    self.do_bench_cudagraph_mem(
  File "/home/testuser/ptd/tritonbench/tritonbench/utils/triton_op.py", line 1215, in do_bench_cudagraph_mem
    raise RuntimeError(
RuntimeError: Cannot capture graph in default stream. Please use side stream in benchmark code.
(B, T, H)
(ptd) testuser@server ➜ ~/ptd/tritonbench git:(main) ✗
% git reset --hard 87dffcc62bb45dee364a874f649b002f48939b5b
HEAD is now at 87dffcc Add proton profiling (#102)
(ptd) testuser@server ➜ ~/ptd/tritonbench git:(main) ✗
% python run.py --op geglu --mode fwd  --precision fp32 --metrics latency,speedup,gpu_peak_mem,mem_footprint_compression_ratio --csv --cudagraph
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:26<00:00,  6.69s/it]
(B, T, H);torch_geglu-gpu_peak_mem;torch_geglu-latency;liger_geglu-gpu_peak_mem;liger_geglu-mem_footprint_compression_ratio;liger_geglu-speedup;liger_geglu-latency;inductor_geglu-gpu_peak_mem;inductor_geglu-mem_footprint_compression_ratio;inductor_geglu-speedup;inductor_geglu-latency
(8, 1024, 4096);2.826960896;46.721439361572266;2.466250752;1.1462585034013606;1.005376512231282;46.47158432006836;2.466250752;1.1462585034013606;1.0054055629276069;46.47024154663086
(8, 2048, 4096);4.538236928;96.66569519042969;3.81681664;1.189010989010989;1.0057531980667247;96.11273956298828;3.81681664;1.189010989010989;1.0278832599519214;94.04345703125
(8, 4096, 4096);7.960788992;190.06402587890625;6.517948416;1.2213642213642213;0.9729716809505725;195.34384155273438;6.517948416;1.2213642213642213;0.9651532339048611;196.92626953125
(8, 8192, 4096);14.80589312;389.8010559082031;11.920211968;1.2420830401125968;0.9981584903324845;390.52020263671875;11.920211968;1.2420830401125968;1.0026486626890936;388.7713317871094
(ptd) testuser@server ➜ ~/ptd/tritonbench git:(main) ✗
```

**Comment by xuzhao9** [comment]
I don't think it is BC-breaking, instead it is because `--cudagraph` never enabled for liger kernels because in the operator it will always set `use_cuda_graphs = False`, which overrides the `--cudagraph` command option.

**Comment by FindHao** [comment]
> I don't think it is BC-breaking, instead it is because `--cudagraph` is _never enabled_ for liger kernels because in the operator it will always set `use_cuda_graphs = False`, which overrides the `--cudagraph` command option. So https://github.com/pytorch-labs/tritonbench/pull/106/files is a bugfix that exposes the issue and actually enables cudagraph on liger kernels.

I see. I only enable it in local testings.

**Comment by FindHao** [comment]
Current cudagraph for liger kernels:
1. bwd included tests fails.
```
 python run.py --op kl_div --mode fwd_bwd  --precision fp32 --metrics latency,speedup --csv  --num-inputs 1 --cudagraph
  0%|                                                                                                                           | 0/1 [00:00<?, ?it/s]
Caught exception, terminating early with partial results
Traceback (most recent call last):
  File "/scratch/yhao/miniconda3/envs/pta_gil/lib/python3.10/site-packages/triton/testing.py", line 79, in do_bench_cudagraph
    fn()
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 690, in <lambda>
    fwd_bwd_fn = lambda: (fwd_fn(), bwd_fn())
  File "/scratch/yhao/pta/tritonbench/tritonbench/operators/kl_div/operator.py", line 59, in <lambda>
    return lambda: y.backward(retain_graph=True)
  File "/scratch/yhao/pta/pytorch/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/scratch/yhao/pta/pytorch/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/scratch/yhao/pta/pytorch/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 782, in run
    y_vals: Dict[str, BenchmarkOperatorMetrics] = functools.reduce(
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 770, in _reduce_benchmarks
    acc[bm_name] = self._do_bench(
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 987, in _do_bench
    metrics.latency = do_bench_wrapper(
  File "/scratch/yhao/pta/tritonbench/tritonbench/components/do_bench/run.py", line 16, in do_bench_wrapper
    return triton.testing.do_bench_cudagraph(
  File "/scratch/yhao/miniconda3/envs/pta_gil/lib/python3.10/site-packages/triton/testing.py", line 74, in do_bench_cudagraph
    with torch.cuda.graph(g):
  File "/scratch/yhao/pta/pytorch/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/scratch/yhao/pta/pytorch/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

(B, T, V)
```
2. if we run fwd_bwd in one function rather than run another fwd function https://github.com/pytorch-labs/tritonbench/compare/main...findhao/add-full-mode , liger's implementation for backward causes cudagraph issues. 
```
% python run.py --op kl_div --mode fwd_bwd  --precision fp32 --metrics latency,speedup --csv  --num-inputs 1 --cudagraph
  0%|                                                                                                                           | 0/1 [00:00<?, ?it/s]
Caught exception, terminating early with partial results
Traceback (most recent call last):
  File "/scratch/yhao/miniconda3/envs/pta_gil/lib/python3.10/site-packages/triton/testing.py", line 79, in do_bench_cudagraph
    fn()
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 693, in <lambda>
    fwd_bwd_fn = lambda: (fwd_fn(), bwd_fn())
  File "/scratch/yhao/pta/tritonbench/tritonbench/operators/kl_div/operator.py", line 59, in <lambda>
    return lambda: y.backward(retain_graph=True)
  File "/scratch/yhao/pta/pytorch/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/scratch/yhao/pta/pytorch/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/scratch/yhao/pta/pytorch/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: operation would make the legacy stream depend on a capturing blocking stream
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 789, in run
    y_vals: Dict[str, BenchmarkOperatorMetrics] = functools.reduce(
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 777, in _reduce_benchmarks
    acc[bm_name] = self._do_bench(
  File "/scratch/yhao/pta/tritonbench/tritonbench/utils/triton_op.py", line 999, in _do_bench
    metrics.latency = do_bench_wrapper(
  File "/scratch/yhao/pta/tritonbench/tritonbench/components/do_bench/run.py", line 16, in do_bench_wrapper
    return triton.testing.do_bench_cudagraph(
  File "/scratch/yhao/miniconda3/envs/pta_gil/lib/python3.10/site-packages/triton/testing.py", line 74, in do_bench_cudagraph
    with torch.cuda.graph(g):
  File "/scratch/yhao/pta/pytorch/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/scratch/yhao/pta/pytorch/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: operation failed due to a previous error during capture
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

(B, T, V)
```
